// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * @typedef {Object} GoWindow
 * @property {Object} go
 * @property {Object} go.main
 * @property {Object} go.main.ResticBrowserApp
 */

/**
 * @type {Window & { go?: { main?: { ResticBrowserApp?: any } } }}
 */
const win = window;

/**
 * @returns {Promise<import('../models').restic.Location>}
 */
export function DefaultRepoLocation() {
  return win.go?.main?.ResticBrowserApp?.DefaultRepoLocation();
}

/**
 * @param {string} arg1
 * @param {import('../models').restic.File} arg2
 * @returns {Promise<string>}
 */
export function DumpFile(arg1, arg2) {
  return win.go?.main?.ResticBrowserApp?.DumpFile(arg1, arg2);
}

/**
 * @param {string} arg1
 * @param {import('../models').restic.File} arg2
 * @returns {Promise<string>}
 */
export function DumpFileToTemp(arg1, arg2) {
  return win.go?.main?.ResticBrowserApp?.DumpFileToTemp(arg1, arg2);
}

/**
 * @param {string} arg1
 * @param {string} arg2
 * @returns {Promise<Array<import('../models').restic.File>>}
 */
export function GetFilesForPath(arg1, arg2) {
  return win.go?.main?.ResticBrowserApp?.GetFilesForPath(arg1, arg2);
}

/**
 * @param {string} arg1
 * @returns {Promise<void>}
 */
export function OpenFileOrUrl(arg1) {
  return win.go?.main?.ResticBrowserApp?.OpenFileOrUrl(arg1);
}

/**
 * @param {import('../models').restic.Location} arg1
 * @returns {Promise<Array<import('../models').restic.Snapshot>>}
 */
export function OpenRepo(arg1) {
  return win.go?.main?.ResticBrowserApp?.OpenRepo(arg1);
}

/**
 * @returns {Promise<string>}
 */
export function ReadPasswordFromFile() {
  return win.go?.main?.ResticBrowserApp?.ReadPasswordFromFile();
}

/**
 * @param {string} arg1
 * @param {import('../models').restic.File} arg2
 * @returns {Promise<string>}
 */
export function RestoreFile(arg1, arg2) {
  return win.go?.main?.ResticBrowserApp?.RestoreFile(arg1, arg2);
}

/**
 * @returns {Promise<string>}
 */
export function SelectLocalRepo() {
  return win.go?.main?.ResticBrowserApp?.SelectLocalRepo();
}
